/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.cmc_clientes;
import dao.cmc_clientesDAO;
import java.awt.Image;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author notedarckbr
 */
public class JDlgcmc_clientes extends javax.swing.JDialog {

    /**
     * Creates new form JDlgcmc_clientes
     */
    
    boolean incluir = false;
    
    public JDlgcmc_clientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Clientes");
        setLocationRelativeTo(null);
        Habilitar(false);

    }
    
    

    public void Habilitar(boolean value) {
        jTxtcmc_bairro.setEnabled(value);
        jTxtcmc_cep.setEnabled(value);
        jTxtcmc_email.setEnabled(value);
        jTxtcmc_endereco.setEnabled(value);
        jTxtcmc_estado.setEnabled(value);
        jTxtcmc_nome.setEnabled(value);
        jTxtcmc_observacoes.setEnabled(value);
        jTxtcmc_id_clientes.setEnabled(value);
        jtxtcmc_cidade.setEnabled(value);
        jFmtcmc_cpf.setEnabled(value);
        jFmtcmc_data_atualizacao.setEnabled(value);
        jFmtcmc_data_criacao.setEnabled(value);
        jFmtcmc_data_de_nascimento.setEnabled(value);
        jFmtcmc_rg.setEnabled(value);
        jFmtcmc_telefone.setEnabled(value);
        jFmtmc_ultima_compra.setEnabled(value);
        jCbocmc_genero.setEnabled(value);
        jChbcmc_status.setEnabled(value);

        jBtnAlterar.setEnabled(!value);
        jBtnCancelar.setEnabled(value);
        jBtnConfirmar.setEnabled(value);
        jBtnExcluir.setEnabled(!value);
        jBtnIncluir.setEnabled(!value);
        jBtnPesquisar.setEnabled(!value);
    }

    public void limpar() {
        jTxtcmc_id_clientes.setText("");
        jTxtcmc_nome.setText("");
        jTxtcmc_bairro.setText("");
        jTxtcmc_estado.setText("");
        jTxtcmc_endereco.setText("");
        jTxtcmc_email.setText("");
        jTxtcmc_cep.setText("");
        jtxtcmc_cidade.setText("");
        jTxtcmc_observacoes.setText("");

        jFmtcmc_cpf.setText("");
        jFmtcmc_data_atualizacao.setText("");
        jFmtcmc_data_criacao.setText("");
        jFmtcmc_data_de_nascimento.setText("");
        jFmtcmc_rg.setText("");
        jFmtcmc_telefone.setText("");
        jFmtmc_ultima_compra.setText("");

        jChbcmc_status.setSelected(false);

        jCbocmc_genero.setSelectedItem(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFmtcmc_cpf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFmtcmc_rg = new javax.swing.JFormattedTextField();
        jTxtcmc_id_clientes = new javax.swing.JTextField();
        jFmtcmc_data_de_nascimento = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtcmc_nome = new javax.swing.JTextField();
        jCbocmc_genero = new javax.swing.JComboBox<>();
        jTxtcmc_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFmtcmc_telefone = new javax.swing.JFormattedTextField();
        jTxtcmc_endereco = new javax.swing.JTextField();
        jTxtcmc_bairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtcmc_cidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTxtcmc_estado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtcmc_cep = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxtcmc_observacoes = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jChbcmc_status = new javax.swing.JCheckBox();
        jFmtcmc_data_criacao = new javax.swing.JFormattedTextField();
        jFmtcmc_data_atualizacao = new javax.swing.JFormattedTextField();
        jFmtmc_ultima_compra = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefone");

        jLabel5.setText("Cpf");

        jLabel6.setText("RG");

        try {
            jFmtcmc_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Codigo");

        try {
            jFmtcmc_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(" ##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFmtcmc_data_de_nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Nome");

        jLabel7.setText("Data de Nascimento");

        jCbocmc_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", "Outros" }));

        jLabel8.setText("Gênero");

        jLabel3.setText("Email");

        jLabel9.setText("Endereço");

        try {
            jFmtcmc_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTxtcmc_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtcmc_bairroActionPerformed(evt);
            }
        });

        jLabel10.setText("Bairro");

        jLabel11.setText("cidade");

        jLabel12.setText("estado");

        jLabel13.setText("cep");

        jLabel14.setText("data criação");

        jLabel15.setText("data atualização");

        jLabel16.setText("ultima compra");

        jLabel17.setText("observações");

        jChbcmc_status.setText("Status");

        try {
            jFmtcmc_data_criacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtcmc_data_criacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtcmc_data_criacaoActionPerformed(evt);
            }
        });

        try {
            jFmtcmc_data_atualizacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFmtmc_ultima_compra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnCancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtnPesquisar)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtcmc_id_clientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtcmc_estado, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtcmc_bairro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtcmc_cidade, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtcmc_cep, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbocmc_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jChbcmc_status)
                        .addGap(38, 38, 38))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtcmc_data_de_nascimento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtcmc_data_criacao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtmc_ultima_compra, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtcmc_data_atualizacao, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtcmc_observacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtcmc_nome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtcmc_endereco, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtcmc_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFmtcmc_rg, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFmtcmc_cpf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFmtcmc_telefone, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtcmc_id_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtcmc_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(jTxtcmc_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtcmc_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtcmc_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtcmc_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtcmc_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addComponent(jTxtcmc_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtcmc_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtcmc_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtcmc_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtcmc_data_de_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jFmtcmc_data_criacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16)
                        .addGap(10, 10, 10)
                        .addComponent(jFmtmc_ultima_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtcmc_data_atualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCbocmc_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbcmc_status)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtcmc_observacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Habilitar(true);
        limpar();
        incluir = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jTxtcmc_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtcmc_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtcmc_bairroActionPerformed

    private void jFmtcmc_data_criacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtcmc_data_criacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtcmc_data_criacaoActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        Habilitar(true);
        incluir = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        cmc_clientes cliente = new cmc_clientes();
        int codigo = Integer.parseInt(jTxtcmc_id_clientes.getText());
        cliente.setCmc_id_clientes(codigo);
        cliente.setCmc_nome(jTxtcmc_nome.getText());
        cliente.setCmc_cpf(jFmtcmc_cpf.getText());
        cliente.setCmc_rg(jFmtcmc_rg.getText());
        cliente.setCmc_data_nascimento(null); // ou jFmtcmc_data_de_nascimento.getText() convertido para Date
        cliente.setCmc_email(jTxtcmc_email.getText());
        cliente.setCmc_telefone(jFmtcmc_telefone.getText());
        cliente.setCmc_endereco(jTxtcmc_endereco.getText());
        cliente.setCmc_bairro(jTxtcmc_bairro.getText());
        cliente.setCmc_cidade(jtxtcmc_cidade.getText());
        cliente.setCmc_estado(jTxtcmc_estado.getText());
        cliente.setCmc_cep(jTxtcmc_cep.getText());
        cliente.setCmc_genero(jCbocmc_genero.getSelectedItem().toString());
        cliente.setCmc_observacoes(jTxtcmc_observacoes.getText());
        cliente.setCmc_data_criacao(null); // ou jFmtcmc_data_criacao.getText() convertido para Date
        cliente.setCmc_data_atualizacao(null); // ou jFmtcmc_data_autualizacao.getText() convertido para Date
        cliente.setCmc_ultima_compra(null); // ou jFmtmc_ultima_compra.getText() convertido para Date

        if (jChbcmc_status.isSelected()) {
            cliente.setCmc_status("S");
        } else {
            cliente.setCmc_status("N");
        }

        cmc_clientesDAO clienteDao = new cmc_clientesDAO();
        if (incluir == true) {
            clienteDao.insert(cliente);
        }else{
        clienteDao.update(cliente);
        }
        
        Habilitar(false);
        limpar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
       int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o cliente?", "Confirmação", JOptionPane.YES_NO_OPTION);
if (opcao == JOptionPane.YES_OPTION) {
    cmc_clientes cliente = new cmc_clientes();
    int codigo = Integer.parseInt(jTxtcmc_id_clientes.getText());
    cliente.setCmc_id_clientes(codigo);
    cliente.setCmc_nome(jTxtcmc_nome.getText());
    cliente.setCmc_bairro(jTxtcmc_bairro.getText());
    cliente.setCmc_cep(jTxtcmc_cep.getText());
    cliente.setCmc_email(jTxtcmc_email.getText());
    cliente.setCmc_endereco(jTxtcmc_endereco.getText());
    cliente.setCmc_estado(jTxtcmc_estado.getText());
    cliente.setCmc_observacoes(jTxtcmc_observacoes.getText());
    cliente.setCmc_cidade(jtxtcmc_cidade.getText());
    cliente.setCmc_cpf(jFmtcmc_cpf.getText());
    cliente.setCmc_rg(jFmtcmc_rg.getText());
    cliente.setCmc_telefone(jFmtcmc_telefone.getText());
    cliente.setCmc_genero(jCbocmc_genero.getSelectedItem().toString());

    // Data de nascimento
    cliente.setCmc_data_nascimento(null);
    cliente.setCmc_ultima_compra(null);

    // Status
    cliente.setCmc_status(jChbcmc_status.isSelected() ? "S" : "N");

    // Datas adicionais
    try {
        java.util.Date dataCriacao = new SimpleDateFormat("dd/MM/yyyy").parse(jFmtcmc_data_criacao.getText());
        cliente.setCmc_data_criacao(new java.sql.Timestamp(dataCriacao.getTime()));
    } catch (Exception e) {
        cliente.setCmc_data_criacao(null);
    }

    try {
        java.util.Date dataAtualizacao = new SimpleDateFormat("dd/MM/yyyy").parse(jFmtcmc_data_atualizacao.getText());
        cliente.setCmc_data_atualizacao(new java.sql.Timestamp(dataAtualizacao.getTime()));
    } catch (Exception e) {
        cliente.setCmc_data_atualizacao(null);
    }


    // DAO
    cmc_clientesDAO clienteDao = new cmc_clientesDAO();
    clienteDao.delete(cliente);

    limpar();
}

    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
     String id = JOptionPane.showInputDialog(null, "Entre com o código do cliente:");
if (id != null && !id.trim().isEmpty()) {
    try {
        int codigo = Integer.parseInt(id);
        cmc_clientesDAO clienteDao = new cmc_clientesDAO();
        cmc_clientes cliente = (cmc_clientes) clienteDao.list(codigo);

        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "Código não existe");
        } else {
            jTxtcmc_id_clientes.setText(id);
            jTxtcmc_nome.setText(cliente.getCmc_nome());
            jTxtcmc_bairro.setText(cliente.getCmc_bairro());
            jTxtcmc_cep.setText(cliente.getCmc_cep());
            jTxtcmc_email.setText(cliente.getCmc_email());
            jTxtcmc_endereco.setText(cliente.getCmc_endereco());
            jTxtcmc_estado.setText(cliente.getCmc_estado());
            jTxtcmc_observacoes.setText(cliente.getCmc_observacoes());
            jtxtcmc_cidade.setText(cliente.getCmc_cidade());
            jFmtcmc_cpf.setText(cliente.getCmc_cpf());
            jFmtcmc_rg.setText(cliente.getCmc_rg());
            jFmtcmc_telefone.setText(cliente.getCmc_telefone());
            jCbocmc_genero.setSelectedItem(cliente.getCmc_genero());

            if (cliente.getCmc_status().equals("S")) {
                jChbcmc_status.setSelected(true);
            } else {
                jChbcmc_status.setSelected(false);
            }

            // Datas
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            if (cliente.getCmc_data_nascimento()!= null)
                jFmtcmc_data_de_nascimento.setText(sdf.format(cliente.getCmc_data_nascimento()));
            if (cliente.getCmc_data_criacao() != null)
                jFmtcmc_data_criacao.setText(sdf.format(cliente.getCmc_data_criacao()));
            if (cliente.getCmc_data_atualizacao() != null)
                jFmtcmc_data_atualizacao.setText(sdf.format(cliente.getCmc_data_atualizacao()));
            if (cliente.getCmc_ultima_compra() != null)
                jFmtmc_ultima_compra.setText(sdf.format(cliente.getCmc_ultima_compra()));
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Código inválido!");
    }
}

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Habilitar(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgcmc_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgcmc_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgcmc_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgcmc_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgcmc_clientes dialog = new JDlgcmc_clientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCbocmc_genero;
    private javax.swing.JCheckBox jChbcmc_status;
    private javax.swing.JFormattedTextField jFmtcmc_cpf;
    private javax.swing.JFormattedTextField jFmtcmc_data_atualizacao;
    private javax.swing.JFormattedTextField jFmtcmc_data_criacao;
    private javax.swing.JFormattedTextField jFmtcmc_data_de_nascimento;
    private javax.swing.JFormattedTextField jFmtcmc_rg;
    private javax.swing.JFormattedTextField jFmtcmc_telefone;
    private javax.swing.JFormattedTextField jFmtmc_ultima_compra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtcmc_bairro;
    private javax.swing.JTextField jTxtcmc_cep;
    private javax.swing.JTextField jTxtcmc_email;
    private javax.swing.JTextField jTxtcmc_endereco;
    private javax.swing.JTextField jTxtcmc_estado;
    private javax.swing.JTextField jTxtcmc_id_clientes;
    private javax.swing.JTextField jTxtcmc_nome;
    private javax.swing.JTextField jTxtcmc_observacoes;
    private javax.swing.JTextField jtxtcmc_cidade;
    // End of variables declaration//GEN-END:variables
}
