/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author notedarckbr
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    private JLabel fundo;

    public JFrmPrincipal() {
        setTitle("Sistema Loja de artigo de tênis de mesa");
        setExtendedState(MAXIMIZED_BOTH);

        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();

        MenuBar.setBackground(new java.awt.Color(12, 76, 120)); // azul claro
        MenuBar.setOpaque(true);
        MenuBar.setBorderPainted(false); // impede que a borda atrapalhe

        jMnuClientes.setBackground(new java.awt.Color(12, 76, 120)); // Azul claro
        jMnuClientes.setOpaque(true);

        jMnuCadastros.setBackground(new java.awt.Color(12, 76, 120)); // Para os itens
        jMnuCadastros.setOpaque(true);

        jMnuFornecedores.setBackground(new java.awt.Color(12, 76, 120)); // Azul claro
        jMnuFornecedores.setOpaque(true);

        jMnuMovimento.setBackground(new java.awt.Color(12, 76, 120)); // Azul claro
        jMnuMovimento.setOpaque(true);

        jMnuProdutos.setBackground(new java.awt.Color(12, 76, 120)); // Azul claro
        jMnuProdutos.setOpaque(true);

        jMnuSair.setBackground(new java.awt.Color(12, 76, 120)); // Azul claro
        jMnuSair.setOpaque(true);

        jMnuUsuarios.setBackground(new java.awt.Color(12, 76, 120)); // Azul claro
        jMnuUsuarios.setOpaque(true);

        jMnuVenda.setBackground(new java.awt.Color(12, 76, 120)); // Azul claro
        jMnuVenda.setOpaque(true);

        jMnuCompra.setBackground(new java.awt.Color(12, 76, 120)); // Azul claro
        jMnuCompra.setOpaque(true);

        // Cria JLabel apenas uma vez
        fundo = new JLabel();
        fundo.setBounds(0, 0, getWidth(), getHeight());
        getContentPane().add(fundo);
        getContentPane().setComponentZOrder(fundo, getContentPane().getComponentCount() - 1);

        // Atualiza imagem depois que o frame for exibido ou redimensionado
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ajustarImagemFundo();
            }

            public void componentResized(java.awt.event.ComponentEvent evt) {
                ajustarImagemFundo();
            }
        });
    }

    private void ajustarImagemFundo() {
        int largura = getWidth();
        int altura = getHeight();

        ImageIcon imagemOriginal = new ImageIcon(getClass().getResource("/img/depositphotos_439247060-stock-illustration-group-ping-pong-players-table.png"));
        Image imagemRedimensionada = imagemOriginal.getImage().getScaledInstance(largura, altura, Image.SCALE_SMOOTH);

        fundo.setIcon(new ImageIcon(imagemRedimensionada));
        fundo.setBounds(0, 0, largura, altura);
        fundo.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JMenuBar();
        jMnuCadastros = new javax.swing.JMenu();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVenda = new javax.swing.JMenuItem();
        jMnuFornecedores = new javax.swing.JMenuItem();
        jMnuCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        MenuBar.setBackground(new java.awt.Color(0, 0, 204));
        MenuBar.setForeground(new java.awt.Color(255, 255, 255));

        jMnuCadastros.setForeground(new java.awt.Color(255, 255, 255));
        jMnuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alguma coisa-Photoroom24px.png"))); // NOI18N
        jMnuCadastros.setMnemonic('c');
        jMnuCadastros.setText("Cadastros");
        jMnuCadastros.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jMnuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCadastrosActionPerformed(evt);
            }
        });

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuClientes.setBackground(new java.awt.Color(0, 51, 204));
        jMnuClientes.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        jMnuClientes.setForeground(new java.awt.Color(255, 255, 255));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes-Photoroom.png"))); // NOI18N
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuClientes);

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuUsuarios.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        jMnuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes-Photoroom.png"))); // NOI18N
        jMnuUsuarios.setText("Usuários");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuUsuarios);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuProdutos.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        jMnuProdutos.setForeground(new java.awt.Color(255, 255, 255));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/24715-NV83ND_lzn-Photoroom.png"))); // NOI18N
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuProdutos);
        jMnuCadastros.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuSair.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        jMnuSair.setForeground(new java.awt.Color(255, 255, 255));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuSair);

        MenuBar.add(jMnuCadastros);

        jMnuMovimento.setForeground(new java.awt.Color(255, 255, 255));
        jMnuMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tabela de movimentos-Photoroom.png"))); // NOI18N
        jMnuMovimento.setMnemonic('m');
        jMnuMovimento.setText("Movimentos");
        jMnuMovimento.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N

        jMnuVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuVenda.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        jMnuVenda.setForeground(new java.awt.Color(255, 255, 255));
        jMnuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/OSLZQS0_lzn-1-Photoroom.png"))); // NOI18N
        jMnuVenda.setText("Venda");
        jMnuMovimento.add(jMnuVenda);

        jMnuFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFornecedores.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        jMnuFornecedores.setForeground(new java.awt.Color(255, 255, 255));
        jMnuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/24715-NV83ND_lzn-1-Photoroom.png"))); // NOI18N
        jMnuFornecedores.setText("Fornecedores");
        jMnuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFornecedoresActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuFornecedores);

        jMnuCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuCompra.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        jMnuCompra.setForeground(new java.awt.Color(255, 255, 255));
        jMnuCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/OSLZQS0_lzn-Photoroom.png"))); // NOI18N
        jMnuCompra.setText("Compra");
        jMnuCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCompraActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuCompra);

        MenuBar.add(jMnuMovimento);

        setJMenuBar(MenuBar);

        setBounds(0, 0, 521, 513);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgcmc_usuarios dlgcmc_usuarios = new JDlgcmc_usuarios(this, true);
        dlgcmc_usuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCadastrosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMnuCadastrosActionPerformed

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        // TODO add your handling code here:
        JDlgcmc_clientes dlgcmc_clientes = new JDlgcmc_clientes(this, true);
        dlgcmc_clientes.setVisible(true);
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        JDlgcmc_produtos dlgcmc_produtos = new JDlgcmc_produtos(this, true);
        dlgcmc_produtos.setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuFornecedoresActionPerformed

    private void jMnuCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu jMnuCadastros;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenuItem jMnuCompra;
    private javax.swing.JMenuItem jMnuFornecedores;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuVenda;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
